#!/bin/bash
# by Aze Santos

LOGFILE=('/tmp/daemon_print.log')

PARSELOG()
{
tail -1 $LOGFILE | grep -wo -e OK -e WARNING -e CRITICAL -e UNKNOWN
}

OUTPUT=$(PARSELOG)

if [ $OUTPUT = OK ];
  then echo OK
  exit 0
elif [ $OUTPUT = WARNING ];
  then echo WARNING
  exit 1
elif [ $OUTPUT = CRITICAL ];
  then echo CRITICAL
  exit 2
else
  echo UNKNOWN
  exit 3
fi
